export const DEFAULT_SLOTS: Record<string, string> = {
  logo_header: '/vercel.svg',
  hero_bg: '/uploads/zhixin-paper-custom-label-rolls-sample-display-showroom.webp',
  vanguard_video: '/uploads/zhixin-paper-label-factory-production-facility-capability.mp4.mp4',
  hub_video_poster: '/uploads/zhixin-paper-label-factory-entrance-facility.webp',
  hub_video: '/uploads/zxpapers-automated-label-manufacturing-and-qc-inspection.mp4.mp4',
  gallery_1: '/uploads/zhixin-paper-high-speed-multi-color-label-printing-machine-scaled.webp',
  gallery_2: '/uploads/Large-Scale-Inventory-Efficient-Warehouse-for-Global-Supply-Chain-Stability.jpg',
  gallery_3: '/uploads/Reliable-Global-Shipping-Bulk-Logistics-for-High-Volume-Label-Orders.webp',
  gallery_4: '/uploads/The-Professional-Team-Behind-Zhixin-Paper-ZXPapers-Label-Manufacturing.webp',
  products_cat_0: '/uploads/zhixin-paper-food-beverage-honey-coffee-jar-labels.webp',
  products_cat_1: '/uploads/zhixin-paper-cosmetic-personal-care-labels-alcohol-wipes.webp',
  products_cat_2: '/uploads/zhixin-paper-industrial-logistics-colored-thermal-roll-labels.webp',
  products_cat_3: '/uploads/zhixin-paper-eco-friendly-bpa-free-fsc-certified-labels.webp',
  products_cat_4: '/uploads/zhixin-paper-luxury-gold-foil-thank-you-custom-labels.webp',
  certifications_img: '/uploads/zhixin-paper-factory-certifications-iso-fda-fsc-sgs.webp',
  logistics_intro_img: '/uploads/Reliable-Global-Shipping-Bulk-Logistics-for-High-Volume-Label-Orders.webp',
  logo_footer: '/vercel.svg',
};
