export const DEFAULT_SLOTS: Record<string, string> = {
  logo_header: 'https://gozhumeng.com/wp-content/uploads/Zhixin-Paper-logo-Professional-thermal-label-and-adhesive-label-manufacturer.png',
  hero_bg: 'https://gozhumeng.com/wp-content/uploads/zhixin-paper-custom-label-rolls-sample-display-showroom.webp',
  vanguard_video: 'https://gozhumeng.com/wp-content/uploads/zhixin-paper-label-factory-production-facility-capability.mp4.mp4',
  hub_video_poster: 'https://gozhumeng.com/wp-content/uploads/zhixin-paper-label-factory-entrance-facility.webp',
  hub_video: 'https://gozhumeng.com/wp-content/uploads/zxpapers-automated-label-manufacturing-and-qc-inspection.mp4.mp4',
  gallery_1: 'https://gozhumeng.com/wp-content/uploads/zhixin-paper-high-speed-multi-color-label-printing-machine-scaled.webp',
  gallery_2: 'https://gozhumeng.com/wp-content/uploads/Large-Scale-Inventory-Efficient-Warehouse-for-Global-Supply-Chain-Stability.jpg',
  gallery_3: 'https://gozhumeng.com/wp-content/uploads/Reliable-Global-Shipping-Bulk-Logistics-for-High-Volume-Label-Orders.webp',
  gallery_4: 'https://gozhumeng.com/wp-content/uploads/The-Professional-Team-Behind-Zhixin-Paper-ZXPapers-Label-Manufacturing.webp',
  products_cat_0: 'https://gozhumeng.com/wp-content/uploads/zhixin-paper-food-beverage-honey-coffee-jar-labels.webp',
  products_cat_1: 'https://gozhumeng.com/wp-content/uploads/zhixin-paper-cosmetic-personal-care-labels-alcohol-wipes.webp',
  products_cat_2: 'https://gozhumeng.com/wp-content/uploads/zhixin-paper-industrial-logistics-colored-thermal-roll-labels.webp',
  products_cat_3: 'https://gozhumeng.com/wp-content/uploads/zhixin-paper-eco-friendly-bpa-free-fsc-certified-labels.webp',
  products_cat_4: 'https://gozhumeng.com/wp-content/uploads/zhixin-paper-luxury-gold-foil-thank-you-custom-labels.webp',
  certifications_img: 'https://gozhumeng.com/wp-content/uploads/zhixin-paper-factory-certifications-iso-fda-fsc-sgs.webp',
  logistics_intro_img: 'https://gozhumeng.com/wp-content/uploads/Reliable-Global-Shipping-Bulk-Logistics-for-High-Volume-Label-Orders.webp',
  logo_footer: 'https://gozhumeng.com/wp-content/uploads/Zhixin-Paper-logo-Professional-thermal-label-and-adhesive-label-manufacturer.png',
};
